<?php

/**
 * @file
 * Contains study_entity.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function study_entity_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the study_entity module.
    case 'help.page.study_entity':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Study Custom Entity') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function study_entity_theme() {
  return [
    'study_entity' => [
      'render element' => 'children',
    ],
  ];
}
