<?php

/**
 * @file
 * Contains field_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function field_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the field_api module.
    case 'help.page.field_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Field API mentoring programm description') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function field_api_theme() {
  return [
    'field_api' => [
      'render element' => 'children',
    ],
  ];
}
